<a href="https://colab.research.google.com/github/amritxcode/machine-learning/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import numpy as np

##array
##1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [110]:
## 2D array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr2.reshape(2,5)
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [111]:
np.arange(1,11,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [112]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
## Attributes of numpy
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size(number of elements):", arr.size)
print("Number of Dimension:", arr.ndim)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size(number of elements): 6
Number of Dimension: 2
Data type: int64
Item size (in bytes): 8


In [115]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

#Element Wise Addition
print("Addition:", arr1 + arr2)
## Element Wise Subtraction
print("Subtraction:", arr1 - arr2)
## Element Wise Multiplication
print("Multiplication:", arr1 * arr2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]


In [116]:
## Universal Function
arr = np.array([1,2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Logarithm
print(np.log(arr))

## Sine
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [117]:

## Array Slicing and Indexing

arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array : \n", arr,'\n')

print(arr[1:,2:],"\n")
print(arr[1:,1:3])

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 7  8]
 [11 12]] 

[[ 6  7]
 [10 11]]


In [118]:
## Modifying Array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [119]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [120]:
## Statistical concepts--Normalization
## To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data - mean) / std_dev

print("Original data:", data)
print("Normalized data:", normalized_data)

Original data: [1 2 3 4 5]
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [121]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data <= 8)]

array([5, 6, 7, 8])